name: Build MangoHud RootFS for Winlator

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      inputMangoHudVersion:
        description: "MangoHud version"
        required: true
        default: "v0.7.1"
      inputMangoHudCommit:
        description: "MangoHud commit hash (optional)"
        required: false
        default: ""
      inputCustomTag:
        description: "Custom tag name"
        required: true
        default: "beta11-mangohud"

env:
  mangohudVer: ${{ github.event.inputs.inputMangoHudVersion }}
  mangohudCommit: ${{ github.event.inputs.inputMangoHudCommit }}
  customTag: ${{ github.event.inputs.inputCustomTag }}

jobs:
  build-rootfs:
    runs-on: ubuntu-24.04-arm
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            arch-bootstrap.sh
            build-mangohud-rootfs.sh

      - name: Setup chroot environment
        run: |
          sudo apt update
          sudo apt install -y coreutils curl sed gawk tar gzip xz-utils zstd python3-pip
          
          # 升级 meson 和 ninja
          pip3 install --upgrade meson ninja mako
          
          # Make arch-bootstrap executable
          chmod +x arch-bootstrap.sh
          sudo cp arch-bootstrap.sh /usr/local/bin/arch-bootstrap
          
          # Create chroot environment
          cd /tmp
          sudo arch-bootstrap -a aarch64 archlinux

      - name: Install build dependencies in chroot
        run: |
          # Create dependency installation script
          cat > /tmp/install-deps.sh << 'EOF'
          #!/bin/bash
          echo "开始系统更新..."
          pacman -Syu --noconfirm
          
          echo "初始化密钥..."
          pacman-key --init 2>/dev/null || true
          
          echo "安装核心构建工具..."
          pacman -S --noconfirm --needed \
            base-devel git cmake meson ninja \
            gcc make pkg-config \
            python python-mako \
            wget curl ca-certificates \
            patchelf tar xz zstd gzip sed gawk

          echo "安装图形和着色器编译工具..."
          pacman -S --noconfirm --needed \
            glslang spirv-tools \
            libx11 libxext libxrandr libxinerama \
            libxdamage libxfixes libdrm \
            mesa libglvnd wayland wayland-protocols \
            libxkbcommon dbus

          echo "安装Vulkan开发包..."
          pacman -S --noconfirm --needed \
            vulkan-headers vulkan-icd-loader vulkan-tools

          echo "依赖安装完成"
          exit 0
          EOF
          
          sudo chmod +x /tmp/install-deps.sh
          sudo cp /tmp/install-deps.sh /tmp/archlinux/
          
          # Mount required filesystems
          sudo mount --bind /proc /tmp/archlinux/proc
          sudo mount --bind /sys /tmp/archlinux/sys
          sudo mount --bind /dev /tmp/archlinux/dev
          
          # Install dependencies in chroot
          sudo chroot /tmp/archlinux /install-deps.sh
          
          # Cleanup
          sudo rm /tmp/archlinux/install-deps.sh

      - name: Prepare build files in chroot
        run: |
          # Copy build script
          sudo cp build-mangohud-rootfs.sh /tmp/archlinux/tmp/
          
          # Create init script with environment variables
          cat > /tmp/init.sh << EOF
          export mangohudVer=$mangohudVer
          export mangohudCommit=$mangohudCommit
          export customTag=$customTag
          EOF
          
          sudo cp /tmp/init.sh /tmp/archlinux/tmp/
          sudo chmod +x /tmp/archlinux/tmp/build-mangohud-rootfs.sh

      - name: Build MangoHud in chroot
        run: |
          # Execute build script in chroot
          sudo chroot /tmp/archlinux /tmp/build-mangohud-rootfs.sh
          
          # Unmount filesystems
          sudo umount -l /tmp/archlinux/dev
          sudo umount -l /tmp/archlinux/sys
          sudo umount -l /tmp/archlinux/proc

      - name: Copy artifacts from chroot
        run: |
          # Create output directory
          mkdir -p artifacts
          
          # Copy built artifacts from chroot
          sudo cp /tmp/archlinux/tmp/output/* ./artifacts/ 2>/dev/null || echo "No artifacts found"
          
          # List artifacts
          echo "构建产物:"
          ls -la ./artifacts/ || echo "No artifacts directory"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: mangohud-${{ github.event.inputs.inputCustomTag }}
          draft: false
          prerelease: false
          tag_name: mangohud-${{ github.event.inputs.inputCustomTag }}
          body: |
            MangoHud Build for Winlator (aarch64)
            
            ## Version Information
            - **MangoHud**: ${{ github.event.inputs.inputMangoHudVersion }}
            - **Commit**: ${{ github.event.inputs.inputMangoHudCommit }}
            - **Custom Tag**: ${{ github.event.inputs.inputCustomTag }}
            
            ## Files Included
            - `mangohud-*.tar.gz`: Standalone MangoHud installation
            - `mangohud-winlator-*.tar.gz`: Pre-integrated package for Winlator
            - `install-mangohud.sh`: Installation script
            
            ## Usage
            Extract the Winlator package to your Winlator rootfs directory, or use the standalone package for other systems.
          files: |
            artifacts/mangohud-*.tar.gz
            artifacts/mangohud-winlator-*.tar.gz
            artifacts/install-mangohud.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mangohud-build-${{ github.event.inputs.inputCustomTag }}
          path: artifacts/

      - name: Cleanup
        if: always()
        run: |
          sudo rm -rf /tmp/archlinux